- name: Set authorized key taken from file
  authorized_key:
    user: ownercz
    state: present
    key: "{{ lookup('file', '/home/ownercz/.ssh/id_ed25519.pub') }}"

- name: Set authorized key taken from file
  authorized_key:
    user: tomet123
    state: present
    key: "{{ lookup('file', 'tomet.pub') }}"
